DELETE FROM dbo.PRODUCT_SUBSCRIPTION_BY_ID;
DELETE FROM dbo.PRODUCT_SUBSCRIBERS;
DELETE FROM dbo.NAMESPACE_MAP;

DELETE FROM dbo.NOTIFICATION_NOTIFICATIONMESSAGE;
DELETE FROM dbo.NOTIFICATIONMESSAGE;

DELETE FROM dbo.INTEREST_NAMESPACE_TYPE;
DELETE FROM dbo.INTEREST_INTEREST_NAMESPACE_TYPE;


DELETE FROM dbo.INTEREST_GROUP_JOINEDWPTYPELIST;
DELETE FROM dbo.INTEREST_GROUP_SHAREDCORELIST;
DELETE FROM dbo.INTEREST_GROUP;

DELETE FROM dbo.LEITSC_INCIDENT;

--DELETE FROM dbo.WorkProduct_associatedInterestGroupIDs;
DELETE FROM dbo.WorkProduct;

DELETE FROM dbo.REGISTERED_SERVICE_SUBSCRIBED_PRODUCT;
DELETE FROM dbo.REGISTERED_SERVICE_PUBLISHED_PRODUCT;

DELETE FROM dbo.PUBLISHED_PRODUCT;
DELETE FROM dbo.SUBSCRIBED_PRODUCT;

DELETE FROM dbo.REGISTERED_SERVICE;

DELETE FROM dbo.INCIDENT_COMMAND_STRUCTURE;
DELETE FROM dbo.INCIDENT_COMMAND_STRUCTURE_INCIDENTS;
DELETE FROM dbo.INCIDENT;

DELETE FROM dbo.USER_INTEREST_GROUP_interestGroupIDList;
DELETE FROM dbo.USER_INTEREST_GROUP;

DELETE FROM dbo.QueuedMessage_interestGroupSet;
DELETE FROM dbo.QueuedMessage;
